import { NextRequest, NextResponse } from "next/server";

import { AiCredentialRequiredError } from "@/lib/ai/credential-service";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { enqueue } from "@/lib/queue";
import { topicsSchema } from "@/lib/zod";

export async function POST(req: NextRequest) {
  try {
    const session = await auth();
    if (!session?.user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await req.json();
    const res = topicsSchema.safeParse(body);

    if (!res.success) {
      console.error(res.error);
      return NextResponse.json({ error: "Invalid input" }, { status: 400 });
    }

    if (!res.data.topics.length) {
      return NextResponse.json(
        { error: "No topics selected" },
        { status: 400 }
      );
    }

    const newMaterial = await prisma.$transaction(
      async (transaction) => {
        const credential = await transaction.aiCredential.findUnique({
          where: { userId: session.user.id },
          select: { id: true },
        });
        if (!credential) throw new AiCredentialRequiredError();

        return transaction.material.create({
          data: {
            title: res.data.moduleName,
            description: "A study material generated by AI",
            userId: session.user.id,
            course: res.data.course || "",
            exam: res.data.exam || "",
            language: res.data.language || "english",
            complexity: res.data.complexity,
            type: res.data.type,
            subject: res.data.subject,
            totalParts: res.data.topics.length,
            Task: {
              create: res.data.topics.map((topic, index) => ({
                topic: topic.name,
                data: topic,
                currIndex: index + 1,
                totalIndex: res.data.topics.length,
              })),
            },
            dispatch: {
              create: { payload: res.data },
            },
          },
        });
      },
      { isolationLevel: "Serializable" }
    );

    const enqueueStatus = await enqueue(res.data, newMaterial.id);
    if (!enqueueStatus) {
      // The database outbox keeps this pending dispatch durable. Worker asks
      // Web to retry it until deterministic Redis jobs are confirmed.
      return NextResponse.json(
        {
          message: "Generation is waiting for the queue.",
          materialId: newMaterial.id,
        },
        { status: 202 }
      );
    }

    await prisma.generationDispatch.deleteMany({
      where: { materialId: newMaterial.id },
    });

    return NextResponse.json({
      message: "Success",
      materialId: newMaterial.id,
    });
  } catch (err) {
    if (err instanceof AiCredentialRequiredError) {
      return NextResponse.json(
        { error: err.message, code: err.code },
        { status: 409 }
      );
    }
    console.error("Generation enqueue failed");
    return NextResponse.json(
      { error: "Some error occured. Please try again later." },
      { status: 500 }
    );
  }
}
