import { NextRequest, NextResponse } from "next/server";

import {
  AiCredentialRequiredError,
  resolveAiCredentialForUser,
} from "@/lib/ai/credential-service";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { enqueue } from "@/lib/queue";
import { topicsSchema } from "@/lib/zod";

export async function POST(req: NextRequest) {
  try {
    const session = await auth();
    if (!session?.user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await req.json();
    const res = topicsSchema.safeParse(body);

    if (!res.success) {
      console.error(res.error);
      return NextResponse.json({ error: "Invalid input" }, { status: 400 });
    }

    if (!res.data.topics.length) {
      return NextResponse.json(
        { error: "No topics selected" },
        { status: 400 }
      );
    }

    await resolveAiCredentialForUser(session.user.id);

    const newMaterial = await prisma.material.create({
      data: {
        title: res.data.moduleName,
        description: "A study material generated by AI",
        userId: session.user.id!,
        course: res.data.course || "",
        exam: res.data.exam || "",
        language: res.data.language || "english",
        complexity: res.data.complexity,
        type: res.data.type,
        subject: res.data.subject,
        totalParts: res.data.topics.length,
      },
    });

    const enqueueStatus = await enqueue(res.data, newMaterial.id);
    if (!enqueueStatus) {
      await prisma.material.delete({ where: { id: newMaterial.id } });
      throw new Error("Failed to enqueue jobs");
    }

    return NextResponse.json({
      message: "Success",
      materialId: newMaterial.id,
    });
  } catch (err) {
    if (err instanceof AiCredentialRequiredError) {
      return NextResponse.json(
        { error: err.message, code: err.code },
        { status: 409 }
      );
    }
    console.error("Generation enqueue failed");
    return NextResponse.json(
      { error: "Some error occured. Please try again later." },
      { status: 500 }
    );
  }
}
